package org.itri.ccma.vsp.datalayer;

// Generated 2013/2/4 ¤W¤È 10:41:39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name = "application", catalog = "vsp")
public class Application implements java.io.Serializable {

	private Long applicationId;
	private Company company;
	private String name;
	private Long hqGroupId;
	private Set<Dashboard> dashboards = new HashSet<Dashboard>(0);

	public Application() {
	}

	public Application(Company company, String name, Long hqGroupId,
			Set<Dashboard> dashboards) {
		this.company = company;
		this.name = name;
		this.hqGroupId = hqGroupId;
		this.dashboards = dashboards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "application_id", unique = true, nullable = false)
	public Long getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Long applicationId) {
		this.applicationId = applicationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "hqGroupID")
	public Long getHqGroupId() {
		return this.hqGroupId;
	}

	public void setHqGroupId(Long hqGroupId) {
		this.hqGroupId = hqGroupId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "application")
	public Set<Dashboard> getDashboards() {
		return this.dashboards;
	}

	public void setDashboards(Set<Dashboard> dashboards) {
		this.dashboards = dashboards;
	}

}
