package org.itri.ccma.vsp.datalayer;

// Generated 2013/2/4 ¤W¤È 10:41:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "vsp")
public class User implements java.io.Serializable {

	private Long userId;
	private String name;
	private String password;
	private String secretKey;
	private String accessKey;
	private Date createTime;
	private Set<User2company> user2companies = new HashSet<User2company>(0);
	private Set<Session> sessions = new HashSet<Session>(0);
	private Set<Dashboard> dashboards = new HashSet<Dashboard>(0);

	public User() {
	}

	public User(String name, String password, String secretKey, String accessKey) {
		this.name = name;
		this.password = password;
		this.secretKey = secretKey;
		this.accessKey = accessKey;
	}

	public User(String name, String password, String secretKey,
			String accessKey, Date createTime,
			Set<User2company> user2companies, Set<Session> sessions,
			Set<Dashboard> dashboards) {
		this.name = name;
		this.password = password;
		this.secretKey = secretKey;
		this.accessKey = accessKey;
		this.createTime = createTime;
		this.user2companies = user2companies;
		this.sessions = sessions;
		this.dashboards = dashboards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "secret_key", nullable = false, length = 128)
	public String getSecretKey() {
		return this.secretKey;
	}

	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}

	@Column(name = "access_key", nullable = false, length = 128)
	public String getAccessKey() {
		return this.accessKey;
	}

	public void setAccessKey(String accessKey) {
		this.accessKey = accessKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<User2company> getUser2companies() {
		return this.user2companies;
	}

	public void setUser2companies(Set<User2company> user2companies) {
		this.user2companies = user2companies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Session> getSessions() {
		return this.sessions;
	}

	public void setSessions(Set<Session> sessions) {
		this.sessions = sessions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Dashboard> getDashboards() {
		return this.dashboards;
	}

	public void setDashboards(Set<Dashboard> dashboards) {
		this.dashboards = dashboards;
	}

}
