package org.itri.ccma.vsp.datalayer;

// Generated 2013/2/4 ¤W¤È 10:41:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dashboard generated by hbm2java
 */
@Entity
@Table(name = "dashboard", catalog = "vsp")
public class Dashboard implements java.io.Serializable {

	private Long dashboardId;
	private Application application;
	private User user;
	private String setting;

	public Dashboard() {
	}

	public Dashboard(Application application, User user, String setting) {
		this.application = application;
		this.user = user;
		this.setting = setting;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dashboard_id", unique = true, nullable = false)
	public Long getDashboardId() {
		return this.dashboardId;
	}

	public void setDashboardId(Long dashboardId) {
		this.dashboardId = dashboardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id")
	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "setting", length = 65535)
	public String getSetting() {
		return this.setting;
	}

	public void setSetting(String setting) {
		this.setting = setting;
	}

}
