package org.itri.ccma.vsp.datalayer;

// Generated 2013/2/4 ¤W¤È 10:41:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hqserver generated by hbm2java
 */
@Entity
@Table(name = "hqserver", catalog = "vsp")
public class Hqserver implements java.io.Serializable {

	private long hqId;
	private Company company;
	private String name;
	private String password;
	private String ip;

	public Hqserver() {
	}

	public Hqserver(long hqId) {
		this.hqId = hqId;
	}

	public Hqserver(long hqId, Company company, String name, String password,
			String ip) {
		this.hqId = hqId;
		this.company = company;
		this.name = name;
		this.password = password;
		this.ip = ip;
	}

	@Id
	@Column(name = "hq_id", unique = true, nullable = false)
	public long getHqId() {
		return this.hqId;
	}

	public void setHqId(long hqId) {
		this.hqId = hqId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ip")
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}
