package org.itri.ccma.vsp.datalayer;

// Generated 2013/2/4 ¤W¤È 10:41:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "session", catalog = "vsp")
public class Session implements java.io.Serializable {

	private long sessionKey;
	private User user;
	private Date loginTime;
	private Date lastActiveTime;

	public Session() {
	}

	public Session(long sessionKey) {
		this.sessionKey = sessionKey;
	}

	public Session(long sessionKey, User user, Date loginTime,
			Date lastActiveTime) {
		this.sessionKey = sessionKey;
		this.user = user;
		this.loginTime = loginTime;
		this.lastActiveTime = lastActiveTime;
	}

	@Id
	@Column(name = "session_key", unique = true, nullable = false)
	public long getSessionKey() {
		return this.sessionKey;
	}

	public void setSessionKey(long sessionKey) {
		this.sessionKey = sessionKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", length = 19)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_active_time", length = 19)
	public Date getLastActiveTime() {
		return this.lastActiveTime;
	}

	public void setLastActiveTime(Date lastActiveTime) {
		this.lastActiveTime = lastActiveTime;
	}

}
