package org.itri.ccma.vsp.datalayer;

// Generated 2013/2/4 ¤W¤È 10:41:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * User2company generated by hbm2java
 */
@Entity
@Table(name = "user2company", catalog = "vsp")
public class User2company implements java.io.Serializable {

	private Long user2companyId;
	private User user;
	private Company company;

	public User2company() {
	}

	public User2company(User user, Company company) {
		this.user = user;
		this.company = company;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user2company_id", unique = true, nullable = false)
	public Long getUser2companyId() {
		return this.user2companyId;
	}

	public void setUser2companyId(Long user2companyId) {
		this.user2companyId = user2companyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

}
